- op: replace
  path: /spec/rules/0/host
  value: app.nonprod.amidostacks.com

- op: add
  path: /spec/tls
  value:
    - hosts:
      - dev.amidostacks.com
      - nonprod.amidostacks.com

- op: add
  path: /spec/rules/-
  value:
    host: "dev.amidostacks.com"
    http:
      paths:
      - path: /web/stacks(/|$)(.*)
        backend:
          serviceName: stacks-webapp
          servicePort: 3000
# 
- op: add
  path: /spec/rules/-
  value:
    host: "app.nonprod.amidostacks.com"
    http:
      paths:
      - path: /web/stacks(/|$)(.*)
        backend:
          serviceName: stacks-webapp
          servicePort: 3000

#for localhost tests
- op: add
  path: /spec/rules/-
  value:
    host: "dev.localhost"
    http:
      paths:
      - path: /web/stacks(/|$)(.*)
        backend:
          serviceName: stacks-webapp
          servicePort: 3000
